language: ruby
cache:
  - bundler
  - node_modules
sudo: false
addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x9ECBEC467F0CEB10'
    packages:
      - mongodb-org-server=3.4.5
services:
  - mongodb
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
  slack:
    secure: NfcNb3LCyd7/ACYc6mDoBJZlBFIV5wKMMWs0On2DNeaDoD/EKCbQRQQVOHEvfsaqOM+5zmi9giYaV7cV+Gl+zfehZ/Q69x89YjWWVFeAp5QGDzoCnM7oaaTXygla52sfcL9Oi3rLgTWyjqMSS7tM2DW5d/V+iEjyilmavsUvRbU=
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"
  - npm install -g eslint
  - cp ./.travis/mongoid.yml ./config/mongoid.yml
script:
  - bundle exec brakeman -qAzw1
  - bundle exec bundle-audit update
  - bundle exec bundle-audit check --ignore CVE-2018-1000544
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
  - travis_retry bundle exec rake test
