cypress_validation_utility:
  build: ./
  ports:
    - "3030:3000"
  command: /rails/cypress-validation-utility/rails-entrypoint.sh
  links:
    - mongodb:mongo
  env_file: .env-prod
  restart: unless-stopped
mongodb:
  image: mongo
  volumes:
    - /data/db:/data/db
  ports:
    - "27017:27017"
  restart: unless-stopped
