js_ecqm_engine:
  image: projectcypress/js-ecqm-engine
  environment:
    - MONGODB_HOST=mongo
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_PORT=5672
  links:
    - mongodb:mongo
    - rabbit:rabbitmq
  restart: unless-stopped
rabbit:
  image: rabbitmq:3-management
  restart: unless-stopped
  ports:
  - "15672:15672"
cypress_validation_utility:
  build: ./
  ports:
    - "3030:3000"
  command: /rails/cypress-validation-utility/rails-entrypoint.sh
  links:
    - mongodb:mongo
    - rabbit:rabbitmq
  env_file: .env-prod
  environment:
  - MONGODB_HOST=mongo
  - RABBITMQ_HOST=rabbitmq
  - RABBITMQ_PORT=5672
  restart: unless-stopped
mongodb:
  image: mongo
  volumes:
    - /data/db:/data/db
    - ./mongo:/etc/mongo
  command: --config=/etc/mongo/docker_mongod.conf
  restart: unless-stopped
  ports:
  - "27019:27017"
