development:
  clients:
    default:
      database: cypress_development
      hosts:
        - <%= ENV.fetch('MONGO_PORT_27017_TCP_ADDR', 'localhost') %>:<%= ENV.fetch('MONGO_PORT_27017_TCP_PORT', '27017') %>
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: cypress_validation_utility_test
      hosts:
        - <%= ENV['TEST_DB_HOST'] || 'localhost' %>:27017
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      database: cypress_validation_utility_production
      hosts:
        - <%= ENV.fetch('MONGO_PORT_27017_TCP_ADDR', 'localhost') %>:<%= ENV.fetch('MONGO_PORT_27017_TCP_PORT', '27017') %>
  options:
    raise_not_found_error: false
