# Mongoid Configureation for Travis CI
development:
  clients:
    default:
      database: cypress_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: cypress_validation_utility_test
      hosts:
        - <%= ENV['TEST_DB_HOST'] || 'localhost' %>:27017
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      database: cypress_production
      hosts:
        - localhost:27017
